name: JS tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14]

    runs-on: ${{ matrix.platform }}

    env:
      TZ: Europe/Berlin
      FORCE_COLOR: 1

    steps:
      - uses: actions/checkout@v2

      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm@7
        run: npm install --global npm@7

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Install bids-validator
        run: |
          npm install
          echo "./node_modules/.bin" >> $GITHUB_PATH

      - name: Eslint
        if: matrix.platform == 'ubuntu-latest'
        run: npm run lint

      - name: Get bids-examples data
        run: git submodule update --init

      - name: Run tests
        run: npm run coverage  -- --maxWorkers=2 --testTimeout=10000

      - name: Upload to codecov
        if: matrix.platform == 'ubuntu-latest'
        run: npm run codecov

      - name: Smoke tests
        run: |
          bids-validator/bin/bids-validator bids-validator/tests/data/valid_headers/ --ignoreNiftiHeaders
          bids-validator/bin/bids-validator bids-validator/tests/data/valid_headers/ --ignoreNiftiHeaders --json

      - name: Build docs
        if: matrix.platform == 'ubuntu-latest'
        run: npm run web-export && rsync -av ./bids-validator-web/out/ ~/web_version
